### PR TITLE
Amd v12

### PR DESCRIPTION
**Pull request by babumoger**
Fix a MBA reset issue and Update the manpage.
## Description

Couple of changes.
1. Fix an MBA reset issue.
    https://github.com/intel/intel-cmt-cat/issues/139
2. update pqos and rdtset manpage

## Affected parts

- [ x] library
- [ x] pqos utility
- [ x] rdtset utility
- [ ] other: (please specify)

## Motivation and Context

Update the manpage and fix a MBA reset issue.

https://github.com/intel/intel-cmt-cat/issues/139
## How Has This Been Tested?

Tested "pqos -R:

Test on Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz and
AMD EPYC 7742 64-Core Processors.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by babumoger** [comment]
Michal/Marcel, Can you please review these patches?

**Comment by babumoger** [comment]
Hope you are all doing good these crazy times. If at all you guys are still working.. please take a look at these patches. I am more interested in patch 1 "lib: Fix MBA reset issue with AMD". thanks

**Comment by aleksinx** [comment]
The changes were merged into master

**Comment by babumoger** [comment]
[AMD Official Use Only - Internal Distribution Only]

Thank you.

**Pull request closed without merging**
